# Generated by Django 5.2.17 on 2026-09-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timetable", "0003_alter_timetableentry_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="top_students/"),
                ),
                ("achievement", models.TextField(blank=True)),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                ("position", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_students",
                        to="timetable.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Student",
                "verbose_name_plural": "Top Students",
                "ordering": ["position", "-average_score", "full_name"],
            },
        ),
    ]
