# Generated by Django 5.2.17 on 2026-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Admission Information", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("required_documents", models.TextField(blank=True)),
                ("important_dates", models.TextField(blank=True)),
                ("application_process", models.TextField(blank=True)),
                ("contact_information", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission Information",
                "verbose_name_plural": "Admission Information",
            },
        ),
    ]
