# Generated by Django 5.2.17 on 2026-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Class Timetable", max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "timetable_file",
                    models.FileField(blank=True, null=True, upload_to="timetables/"),
                ),
                (
                    "timetable_image",
                    models.ImageField(blank=True, null=True, upload_to="timetables/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Timetable",
                "verbose_name_plural": "Timetables",
                "ordering": ["-updated_at"],
            },
        ),
    ]
