# Generated by Django 5.2.17 on 2026-09-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_studentgroup_timetableentry_delete_timetable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="day",
            field=models.CharField(
                choices=[
                    ("monday", "Dúyshembi"),
                    ("tuesday", "Seyshembi"),
                    ("wednesday", "Sárshembi"),
                    ("thursday", "Beishembi"),
                    ("friday", "Juma"),
                    ("saturday", "Shembi"),
                ],
                max_length=20,
            ),
        ),
    ]
